spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # 시작 시 데이터베이스 초기화
    show-sql: true      # 쿼리문 보여줌
    properties:
      hibernate:
        format_sql: true  # 쿼리문 가독성 있게 띄워줌
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

mail: #관리자 권한 메일
  address:
    admin: admin@mail.com